BEGIN TRANSACTION;
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,3,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,3,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,3,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,2,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,2,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,2,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,2,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(14,4,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(15,4,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(16,4,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(21,6,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(22,6,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(23,6,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(24,6,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(25,12,'add_product','Can add product');
INSERT INTO "auth_permission" VALUES(26,12,'change_product','Can change product');
INSERT INTO "auth_permission" VALUES(27,12,'delete_product','Can delete product');
INSERT INTO "auth_permission" VALUES(28,12,'view_product','Can view product');
INSERT INTO "auth_permission" VALUES(29,8,'add_notification','Can add notification');
INSERT INTO "auth_permission" VALUES(30,8,'change_notification','Can change notification');
INSERT INTO "auth_permission" VALUES(31,8,'delete_notification','Can delete notification');
INSERT INTO "auth_permission" VALUES(32,8,'view_notification','Can view notification');
INSERT INTO "auth_permission" VALUES(33,9,'add_order','Can add order');
INSERT INTO "auth_permission" VALUES(34,9,'change_order','Can change order');
INSERT INTO "auth_permission" VALUES(35,9,'delete_order','Can delete order');
INSERT INTO "auth_permission" VALUES(36,9,'view_order','Can view order');
INSERT INTO "auth_permission" VALUES(37,11,'add_payment','Can add payment');
INSERT INTO "auth_permission" VALUES(38,11,'change_payment','Can change payment');
INSERT INTO "auth_permission" VALUES(39,11,'delete_payment','Can delete payment');
INSERT INTO "auth_permission" VALUES(40,11,'view_payment','Can view payment');
INSERT INTO "auth_permission" VALUES(41,10,'add_orderitem','Can add order item');
INSERT INTO "auth_permission" VALUES(42,10,'change_orderitem','Can change order item');
INSERT INTO "auth_permission" VALUES(43,10,'delete_orderitem','Can delete order item');
INSERT INTO "auth_permission" VALUES(44,10,'view_orderitem','Can view order item');
INSERT INTO "auth_permission" VALUES(45,7,'add_cartitem','Can add cart item');
INSERT INTO "auth_permission" VALUES(46,7,'change_cartitem','Can change cart item');
INSERT INTO "auth_permission" VALUES(47,7,'delete_cartitem','Can delete cart item');
INSERT INTO "auth_permission" VALUES(48,7,'view_cartitem','Can view cart item');
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
INSERT INTO "auth_user" VALUES(1,'pbkdf2_sha256$1500000$oTm3m49vrnC6bGd4clvnDr$qTcbiMtGyEHdTbJ+sKXnUUksqLdR1VLojzfijZu/LL0=','2026-10-06 10:29:25.541533',1,'admin','','admin@shop.in',1,1,'2026-10-06 10:17:40.577005','');
INSERT INTO "auth_user" VALUES(2,'pbkdf2_sha256$29000$AoX6PFJvlZTw$TIXq0yAnP9hxa7ZLOqTfCJT+6ewTdxa+Cl2iAbtkRQk=',NULL,0,'prakash10253@gmail.com','','prakash10253@gmail.com',0,1,'2026-10-06 10:21:50.572827','Prakash .R');
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','group');
INSERT INTO "django_content_type" VALUES(3,'auth','permission');
INSERT INTO "django_content_type" VALUES(4,'auth','user');
INSERT INTO "django_content_type" VALUES(5,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(6,'sessions','session');
INSERT INTO "django_content_type" VALUES(7,'shop','cartitem');
INSERT INTO "django_content_type" VALUES(8,'shop','notification');
INSERT INTO "django_content_type" VALUES(9,'shop','order');
INSERT INTO "django_content_type" VALUES(10,'shop','orderitem');
INSERT INTO "django_content_type" VALUES(11,'shop','payment');
INSERT INTO "django_content_type" VALUES(12,'shop','product');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'contenttypes','0001_initial','2026-10-06 10:17:40.190462');
INSERT INTO "django_migrations" VALUES(2,'auth','0001_initial','2026-10-06 10:17:40.198630');
INSERT INTO "django_migrations" VALUES(3,'admin','0001_initial','2026-10-06 10:17:40.203310');
INSERT INTO "django_migrations" VALUES(4,'admin','0002_logentry_remove_auto_add','2026-10-06 10:17:40.207897');
INSERT INTO "django_migrations" VALUES(5,'admin','0003_logentry_add_action_flag_choices','2026-10-06 10:17:40.210937');
INSERT INTO "django_migrations" VALUES(6,'contenttypes','0002_remove_content_type_name','2026-10-06 10:17:40.218601');
INSERT INTO "django_migrations" VALUES(7,'auth','0002_alter_permission_name_max_length','2026-10-06 10:17:40.223224');
INSERT INTO "django_migrations" VALUES(8,'auth','0003_alter_user_email_max_length','2026-10-06 10:17:40.227266');
INSERT INTO "django_migrations" VALUES(9,'auth','0004_alter_user_username_opts','2026-10-06 10:17:40.230296');
INSERT INTO "django_migrations" VALUES(10,'auth','0005_alter_user_last_login_null','2026-10-06 10:17:40.235239');
INSERT INTO "django_migrations" VALUES(11,'auth','0006_require_contenttypes_0002','2026-10-06 10:17:40.236121');
INSERT INTO "django_migrations" VALUES(12,'auth','0007_alter_validators_add_error_messages','2026-10-06 10:17:40.239632');
INSERT INTO "django_migrations" VALUES(13,'auth','0008_alter_user_username_max_length','2026-10-06 10:17:40.244168');
INSERT INTO "django_migrations" VALUES(14,'auth','0009_alter_user_last_name_max_length','2026-10-06 10:17:40.248094');
INSERT INTO "django_migrations" VALUES(15,'auth','0010_alter_group_name_max_length','2026-10-06 10:17:40.256904');
INSERT INTO "django_migrations" VALUES(16,'auth','0011_update_proxy_permissions','2026-10-06 10:17:40.259796');
INSERT INTO "django_migrations" VALUES(17,'auth','0012_alter_user_first_name_max_length','2026-10-06 10:17:40.264689');
INSERT INTO "django_migrations" VALUES(18,'sessions','0001_initial','2026-10-06 10:17:40.267204');
INSERT INTO "django_migrations" VALUES(19,'shop','0001_initial','2026-10-06 10:17:40.290175');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO "django_session" VALUES('j0g3ett1p4xvrezq69c1yyutjymkqyds','.eJxVjEEOwiAQRe_C2hB0EDou3fcMZIYBqRpISrsy3l2bdKHb_977LxVoXUpYe5rDJOqijurwuzHFR6obkDvVW9Ox1WWeWG-K3mnXY5P0vO7u30GhXr51tGefTgkQGAEYLDlvHLP1JqFBspmdyGCJMw1ZfHYgAJjZAyKyV-8P4u44IQ:1xDxGv:5VPP8yroNXqZ0FMwZ8Womh_Yy4LNXdoHJ_eyIaFnwp8','2026-10-20 10:29:25.542782');
CREATE TABLE "shop_cartitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" integer unsigned NOT NULL CHECK ("quantity" >= 0), "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "shop_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "type" varchar(30) NOT NULL, "message" varchar(255) NOT NULL, "is_read" bool NOT NULL, "created_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "shop_notification" VALUES(1,'order_confirmation','Payment received. Order #1 (Rs 3,499.00) is confirmed.',0,'2026-10-06 10:22:03.466160',2);
CREATE TABLE "shop_order" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "total" decimal NOT NULL, "payment_status" varchar(20) NOT NULL, "order_status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "shop_order" VALUES(1,3499,'paid','processing','2026-10-06 10:22:03.452300',2);
CREATE TABLE "shop_orderitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "quantity" integer unsigned NOT NULL CHECK ("quantity" >= 0), "price" decimal NOT NULL, "order_id" bigint NOT NULL REFERENCES "shop_order" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "shop_orderitem" VALUES(1,1,3499,1,6);
CREATE TABLE "shop_payment" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "amount" decimal NOT NULL, "payment_method" varchar(30) NOT NULL, "transaction_id" varchar(120) NOT NULL, "status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "order_id" bigint NOT NULL REFERENCES "shop_order" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "shop_payment" VALUES(1,3499,'demo','demo_1','success','2026-10-06 10:22:03.452300',1);
CREATE TABLE "shop_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(120) NOT NULL, "description" text NOT NULL, "category" varchar(60) NOT NULL, "price" decimal NOT NULL, "stock" integer unsigned NOT NULL CHECK ("stock" >= 0), "image" varchar(100) NOT NULL, "sold" integer unsigned NOT NULL CHECK ("sold" >= 0));
INSERT INTO "shop_product" VALUES(1,'Aero Headphones','Aero Headphones - great value.','Audio',2999,14,'',98);
INSERT INTO "shop_product" VALUES(2,'Trail Backpack','Trail Backpack - great value.','Outdoor',1999,3,'',80);
INSERT INTO "shop_product" VALUES(3,'Pulse Watch','Pulse Watch - great value.','Wearables',8999,22,'',92);
INSERT INTO "shop_product" VALUES(4,'Beam Speaker','Beam Speaker - great value.','Audio',1499,2,'',75);
INSERT INTO "shop_product" VALUES(5,'Summit Bottle','Summit Bottle - great value.','Outdoor',599,60,'',60);
INSERT INTO "shop_product" VALUES(6,'Loop Keyboard','Loop Keyboard - great value.','Desk',3499,17,'',71);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "shop_notification_user_id_24ae0d8a" ON "shop_notification" ("user_id");
CREATE INDEX "shop_order_user_id_00aba627" ON "shop_order" ("user_id");
CREATE INDEX "shop_payment_order_id_20828773" ON "shop_payment" ("order_id");
CREATE INDEX "shop_orderitem_order_id_2f1b00cf" ON "shop_orderitem" ("order_id");
CREATE INDEX "shop_orderitem_product_id_48153f22" ON "shop_orderitem" ("product_id");
CREATE INDEX "shop_cartitem_user_id_5a7eba01" ON "shop_cartitem" ("user_id");
CREATE INDEX "shop_cartitem_product_id_09e4b7dd" ON "shop_cartitem" ("product_id");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('django_migrations',19);
INSERT INTO "sqlite_sequence" VALUES('django_admin_log',0);
INSERT INTO "sqlite_sequence" VALUES('django_content_type',12);
INSERT INTO "sqlite_sequence" VALUES('auth_permission',48);
INSERT INTO "sqlite_sequence" VALUES('auth_group',0);
INSERT INTO "sqlite_sequence" VALUES('auth_user',2);
INSERT INTO "sqlite_sequence" VALUES('shop_product',6);
INSERT INTO "sqlite_sequence" VALUES('shop_cartitem',1);
INSERT INTO "sqlite_sequence" VALUES('shop_order',1);
INSERT INTO "sqlite_sequence" VALUES('shop_orderitem',1);
INSERT INTO "sqlite_sequence" VALUES('shop_payment',1);
INSERT INTO "sqlite_sequence" VALUES('shop_notification',1);
COMMIT;
